import AppKit
import Observation

/// One thing the user copied.
struct ClipboardItem: Identifiable, Equatable {
    enum Kind: String {
        case text
        case url
        case color
        case image

        var symbolName: String {
            switch self {
            case .text: return "text.alignleft"
            case .url: return "link"
            case .color: return "paintpalette"
            case .image: return "photo"
            }
        }
    }

    let id = UUID()
    var kind: Kind
    /// What goes back on the pasteboard, and what the row shows. Empty for an image.
    var text: String
    var image: NSImage?
    var copiedAt: Date
    /// Pinned items survive eviction when the history is full.
    var isPinned: Bool = false

    /// The colour a `.color` item names, for the swatch on its row.
    var color: NSColor? {
        guard kind == .color else { return nil }
        return ClipboardHistoryService.parseColor(text)
    }

    static func == (lhs: ClipboardItem, rhs: ClipboardItem) -> Bool {
        lhs.id == rhs.id && lhs.isPinned == rhs.isPinned
    }
}

/// Remembers what has been copied, so something one clipboard ago is still reachable.
///
/// Polled, because AppKit has no notification for the pasteboard changing: the only signal
/// is `NSPasteboard.changeCount`, an integer that has to be watched. That read is very
/// cheap, which matters for the decision below.
///
/// **Unlike the other sampling services, this one does not stop when its view goes away.**
/// `SystemStatsService` and `BluetoothBatteryService` are reference counted to the view that
/// displays them because nothing is lost by not sampling while nobody is looking. A
/// clipboard history is the opposite: copying happens while the user is working in another
/// app, which is exactly when the notch is closed, so a history that only recorded while its
/// own widget was on screen would record almost nothing and be worse than not existing. It
/// polls whenever the feature is switched on. The reference count is still here and still
/// used, but it raises the rate while the widget is visible rather than gating the timer.
///
/// Two things it deliberately does not do. It never writes history to disk: people copy
/// passwords, and a menu bar utility silently persisting them is not a trade worth making.
/// And it skips anything a source app marked concealed or transient, which is the convention
/// password managers use to say "do not remember this".
@Observable
@MainActor
final class ClipboardHistoryService {
    private(set) var items: [ClipboardItem] = []

    @ObservationIgnored private var settings: SettingsStore?
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var observers = 0
    @ObservationIgnored private var lastChangeCount = NSPasteboard.general.changeCount

    /// The convention password managers use to opt out of clipboard managers. Not an Apple
    /// API, but honoured by 1Password, Bitwarden, and the rest, and the only signal there is.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    /// Slow enough to be free, quick enough that the newest copy is already there by the
    /// time the panel has finished opening.
    private static let idleInterval: TimeInterval = 1.0
    private static let visibleInterval: TimeInterval = 0.25

    init() {}

    func start(settings: SettingsStore) {
        self.settings = settings
        settingsChanged()
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        items.removeAll()
    }

    /// Starts or stops the poll to match the setting, and clears the history when the
    /// feature is switched off rather than leaving it in memory unreachable.
    func settingsChanged() {
        guard let settings, settings.advanced.clipboardHistoryEnabled, FeatureFlag.clipboardHistory.isEnabled else {
            timer?.invalidate()
            timer = nil
            items.removeAll()
            return
        }
        restartTimer()
        enforceLimit()
    }

    /// Raises the poll rate while the widget is on screen. See the note on the type: this
    /// does not start or stop recording, only how promptly a new copy shows up.
    func beginSampling() {
        observers += 1
        guard observers == 1 else { return }
        restartTimer()
        poll()
    }

    func endSampling() {
        observers = max(0, observers - 1)
        guard observers == 0 else { return }
        restartTimer()
    }

    // MARK: Actions

    /// Puts an item back on the pasteboard.
    ///
    /// Moves it to the top rather than recording a second copy of it, and tells the poll to
    /// ignore the change this caused, so clicking a row does not leave the list holding the
    /// same thing twice.
    func copyToPasteboard(_ item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch item.kind {
        case .image:
            if let image = item.image { pasteboard.writeObjects([image]) }
        case .text, .url, .color:
            pasteboard.setString(item.text, forType: .string)
        }

        lastChangeCount = pasteboard.changeCount

        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var moved = items.remove(at: index)
        moved.copiedAt = Date()
        items.insert(moved, at: 0)
        sortPinnedFirst()
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].isPinned.toggle()
        sortPinnedFirst()
        enforceLimit()
    }

    func remove(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
    }

    /// Empties the history, pinned items included.
    ///
    /// Pinning protects an item from being pushed out by the limit, not from being deleted
    /// on purpose. A Clear that quietly left things behind would be the more surprising of
    /// the two behaviours.
    func clearAll() {
        items.removeAll()
    }

    // MARK: Polling

    private func restartTimer() {
        timer?.invalidate()
        timer = nil

        guard let settings, settings.advanced.clipboardHistoryEnabled, FeatureFlag.clipboardHistory.isEnabled else { return }

        let interval = observers > 0 ? Self.visibleInterval : Self.idleInterval
                let timer = Timer.onMain(every: interval) { [weak self] in
            self?.poll()
        }
        self.timer = timer
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // A source app asking not to be remembered is honoured before anything is read.
        let available = pasteboard.types ?? []
        guard !Self.concealedTypes.contains(where: available.contains) else { return }

        guard let item = read(pasteboard) else { return }

        // Consecutive identical copies are one entry. Pressing copy twice on the same
        // selection is not two pieces of history.
        // Compared against the most recently copied item, not the first in the list: the
        // list is sorted pinned-first, so `items.first` is whichever pin happens to be
        // newest rather than the last thing the user actually copied.
        if let newest = items.max(by: { $0.copiedAt < $1.copiedAt }),
           newest.kind == item.kind, newest.text == item.text, item.kind != .image {
            return
        }

        items.insert(item, at: 0)
        sortPinnedFirst()
        enforceLimit()
    }

    private func read(_ pasteboard: NSPasteboard) -> ClipboardItem? {
        // Image first: a copied image often carries a filename string alongside it, and the
        // picture is the thing the user meant.
        if let image = NSImage(pasteboard: pasteboard), image.isValid,
           pasteboard.data(forType: .tiff) != nil || pasteboard.data(forType: .png) != nil {
            return ClipboardItem(kind: .image, text: "", image: image, copiedAt: Date())
        }

        guard let string = pasteboard.string(forType: .string), !string.isEmpty else { return nil }
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        if Self.parseColor(trimmed) != nil {
            return ClipboardItem(kind: .color, text: trimmed, image: nil, copiedAt: Date())
        }
        if Self.isWebURL(trimmed) {
            return ClipboardItem(kind: .url, text: trimmed, image: nil, copiedAt: Date())
        }
        return ClipboardItem(kind: .text, text: string, image: nil, copiedAt: Date())
    }

    /// A URL only when it has a scheme and a host. Without the host check every sentence
    /// with a colon in it was filed as a link.
    static func isWebURL(_ string: String) -> Bool {
        guard !string.contains(" "), string.count < 2048,
              let url = URL(string: string),
              let scheme = url.scheme?.lowercased()
        else { return false }
        return (scheme == "http" || scheme == "https") && (url.host?.isEmpty == false)
    }

    /// Recognises `#rgb`, `#rrggbb`, and `#rrggbbaa`, which is what a design tool copies.
    nonisolated static func parseColor(_ string: String) -> NSColor? {
        var hex = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard hex.hasPrefix("#") else { return nil }
        hex.removeFirst()

        guard [3, 6, 8].contains(hex.count), hex.allSatisfy(\.isHexDigit) else { return nil }
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }

        guard let value = UInt64(hex, radix: 16) else { return nil }
        let hasAlpha = hex.count == 8
        let shift = hasAlpha ? 8 : 0

        return NSColor(
            srgbRed: CGFloat((value >> (16 + shift)) & 0xFF) / 255,
            green: CGFloat((value >> (8 + shift)) & 0xFF) / 255,
            blue: CGFloat((value >> shift) & 0xFF) / 255,
            alpha: hasAlpha ? CGFloat(value & 0xFF) / 255 : 1
        )
    }

    /// Pinned first, then newest first inside each group.
    private func sortPinnedFirst() {
        items.sort { left, right in
            if left.isPinned != right.isPinned { return left.isPinned }
            return left.copiedAt > right.copiedAt
        }
    }

    /// Trims to the limit, counting only unpinned items. Pinning something is a statement
    /// that it should outlive the limit, so a history full of pins simply stops evicting.
    private func enforceLimit() {
        guard let settings else { return }
        let limit = settings.advanced.clipboardHistoryLimit

        var unpinned = 0
        items = items.filter { item in
            guard !item.isPinned else { return true }
            unpinned += 1
            return unpinned <= limit
        }
    }
}

#if DEBUG
extension ClipboardHistoryService {
    /// Fixed history for a capture.
    ///
    /// Sample data rather than the real pasteboard, and not only for determinism: a capture
    /// writes a PNG to disk, and whatever the user last copied has no business ending up in
    /// one.
    func applySample() {
        items = [
            ClipboardItem(kind: .url, text: "https://lrclib.net/api/search", image: nil,
                          copiedAt: Date(), isPinned: true),
            ClipboardItem(kind: .color, text: "#3A7BD5", image: nil, copiedAt: Date()),
            ClipboardItem(kind: .text, text: "AudioHardwareCreateProcessTap", image: nil, copiedAt: Date()),
            ClipboardItem(kind: .text, text: "The quick brown fox jumps over the lazy dog", image: nil,
                          copiedAt: Date())
        ]
    }
}
#endif
